### ISSUE TITLE
--optional flag seems to be broken

### ISSUE THREAD

**Issue by kasperekt** [babel/babelify#102]
I have this command: `watchify app/scripts/app.jsx -t [ babelify --optional es6.spec.symbols ] --outfile dist/js/build.js --extension=.jsx --extension=.js`

When I open my app on Safari 8 (which of course doesn't have `Symbol()` support) I get this error:

```
ReferenceError: Can't find variable: Symbol
```
When I include `babel-polyfill.js` file in **index.html** it works fine. So it seems something is wrong, or am I doing it wrong?

**Comment by zertosh** [comment]
`--optional` works, it's just that [`es6.spec.symbols`](http://babeljs.io/docs/advanced/transformers/es6/spec-symbols/)  is for better spec compliance, not for including the runtime. You have two choices:

1. You can either require the polyfill (either from babelify or babel or babel-core) in your entry file; or
2. Install `babel-runtime` and use `--optional runtime`.

I recommend option 2 since that'll result in builds that only have those bits of runtime that you actually use.

**Comment by kasperekt** [comment]
Yes, thank you, that explains a lot. I used `import 'babelify/polyfill'`
