### ISSUE TITLE
Simplest hello-world outputs a bloated bundle file with 20,000 lines... wtf?

### ISSUE THREAD

**Issue by zenjs** [babel/babelify#105]
Hi there!
I was looking for a way to write React classes in ES6 and followed the following hello world simplest example - http://www.jayway.com/2015/03/04/using-react-with-ecmascript-6/
as you can see it is the simplest hello world example you could come up with and it is using babelify.
The output file is bloated with 20,000 lines of es5 and comes up to 1.6 MB in size!!!
This is of course before you started to actually writing your app... I've hear people developing apps and reaching to a size of 12MB in development and after minify & uglify they managed to reduce it to 4MB...
this is of course a deal-breaker... is this normal? am I doing anything wrong? should I be doing anything extra apart from uglify to get reasonable file size?

**Comment by zertosh** [comment]
It's not normal to go from 12MB dev to 4MB prod. The sizes you're describing have nothing to do with babel/ES6 though. The example from the blog post breaks down like this:

```js
// browserify index.jsx --extension=.jsx -t [ babelify ] | wc -c
627088
// browserify index.jsx --extension=.jsx --debug -t [ babelify ] | wc -c
1599295
// browserify index.jsx --extension=.jsx -t [ babelify ] | uglifyjs -cm | wc -c
189904
// browserify index.jsx --extension=.jsx -t [ babelify ] | uglifyjs -cm | gzip | wc -c
52144
```

Source maps pretty much double the size of any file – 627kb vs 1.6mb. But that's fine because you don't ship source maps, they're a developer convenience. After you minify, it drops to 189kb. Most of that is React (in this example). But that's fine because that's a fixed cost that doesn't grow with your app size. Furthermore, you'll probably deliver your assets via a server/CDN that gzips, and then you're only talking about 52kb.

Now, if you're talking about the `class` helpers, then I suggest you look into using the [runtime](http://babeljs.io/docs/usage/runtime/) or the [external-helpers](http://babeljs.io/docs/advanced/external-helpers/). With those, babel won't be inlining the helpers for each file, but rather reference them via a global or another module.
