### ISSUE TITLE
"SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'"

### ISSUE THREAD

**Issue by vgoklani** [babel/babelify#136]
Not sure what's going on, but this message just started showing up...

"SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'"

Here's the relevant bit from my gulp file:

    'use strict';

    var gulp = require('gulp'),
        notify = require("gulp-notify"),
        babelify = require('babelify'),
        browserify = require('browserify'),
        browserSync = require('browser-sync'),
        source = require('vinyl-source-stream'),
        uglify = require('gulp-uglify'),
        buffer = require('vinyl-buffer');

    var vendors = [
      'jquery',
      'moment',
      'd3',
      'queue-async',
      'react',
      'react-dom',
      'react-bootstrap',
      'react-infinite',
      'lodash',
      'rc-switch',
      'rc-slider',
      'he',
      'react-debounce-input',
      'react-swipe-views',
      'react-modal',
    ];

    gulp.task('app', function () {
        var stream = browserify({
                entries: ['./app/app.jsx'],
                transform: [babelify],
                debug: false,
                extensions: ['.jsx'],
                fullPaths: false
            });

        vendors.forEach(function(vendor) {
            stream.external(vendor);
        });

        return stream.bundle()
                     .pipe(source('build.min.js'))
                     .pipe(buffer())
                     .pipe(uglify())
                     .pipe(gulp.dest('build/js'))
                     .pipe(notify("Successfully built build.min.js file!"));

    });

I'm not sure what happened, but things were fine just a few days ago. Thanks!

**Comment by zertosh** [comment]
You upgraded to babelify 7.0, which uses the new babel 6.0, and you're missing options. Please checkout the README.

**Comment by rob2d** [comment]
not very helpful! I have read through all of the docs and am having the same issues...

**Comment by zertosh** [comment]
@rob2d Can you provide me with a repo that I can use to reproduce the issue?

**Comment by rob2d** [comment]
Apparently seems to be an issue with the newest babelify. After
downgrading, everything works perfectly. At this rate will be switching to
webpack but thanks anyway! Documentation on this kind of sucks and
everything is broken w React JS and ES6.

**Comment by zertosh** [comment]
The newest babelify uses the newest babel. The options it takes changed completely. The users that have been having the "SyntaxError: 'import' and 'export'..." problem are having it as a result of updating babelify but not updating the options they pass to it. So they end up with untranspiled code which produces some kind syntax error.

**Comment by zertosh** [comment]
> After downgrading, everything works perfectly

That goes to show that you're likely not passing the correct options. Correct babel 5 options don't work for babel 6, and correct babel 6 options don't work for babel 5.

**Comment by rob2d** [comment]
Nope. Changed the options along with it. Apparently everyone using the
Material UI latest branch is having the same issues. The documentation is
also pretty over elaborate. If you want people to use your library, it
would be a good idea not to make it a hassle or respond in a dickish manner
to people who use it. Improving the documentation or simply giving a few
hints or a simple list would go a lot further to keep developers without
years of time to configure things to use your product.

**Comment by zertosh** [comment]
I'm sorry you feel that way. I offered to personally debug your issue if you provided me with some code. I didn't meant to offend. Please remember that we're all volunteers here and just trying to make cool things.

**Comment by jmm** [comment]
@rob2d I understand your frustration, but...I could definitely show you maintainers responding in a d****** manner, but I'm really not seeing it here (unless editing has happened, which I doubt).

> not very helpful! I have read through all of the docs and am having the same issues...

By the same token, there's nothing that can be done for you without a better explanation of what you're experiencing, preferably, as @zertosh said, in the form of a repo with a minimal reproduction. Simply posting a comment on another user's closed issue, who probably was having the stated problem, saying that you're having the same problem doesn't give anyone anything to go on to help you, except for @zertosh's suggestion that your problem probably has the same cause as the OP's, which you took exception to. Your followup comments haven't provided more information either, except that the problem may relate to:

> using the Material UI latest branch

I don't know what that is. That suggests that there may be some problem specific to whatever that is. There's no telling at this point.

> The documentation is also pretty over elaborate.

I would be surprised if there isn't room for improvement in the documentation (there certainly is a lot of room for it with Babel itself), but again, there's nothing specific here to go on.

> or simply giving a few hints or a simple list

I don't know what the hints or list items would be. The hint given to the OP here was to configure options, which is all that a lot of people were missing (many because they simply transitioned to a new major version without looking into what changed).

You're free to switch to Webpack, but I imagine you'll be disappointed if you think that means you won't have to learn how to configure it or won't have any problems. I've seen a number of reports recently from people having problems using Webpack with Babel. Especially consider that most (all?) people using Babel with Webpack probably use the [https://github.com/babel/babel-loader](babel-loader) plugin that's also under the umbrella of this same organization.

**Comment by jmm** [comment]
@rob2d If you decide you want to try to create a minimal repro and you need help getting started, you can check this out: https://github.com/miniminirepro/babelify. It also serves as a working "hello world" example with `babelify@7`.

@zertosh pretty much does everything with babelify and I have no idea how he'd feel about continuing to assist you at this point, but you could also try asking on the Babel Slack, discussion forum, or Stack Overflow. You can see the `babel/babel` `README` for links. In any case, it's worth noting that the tone of the interaction in any of those places will affect people's disposition and willingness to help.

**Comment by rob2d** [comment]
Thanks for all of the help Jesse. I typically do not have an issue
interacting with others as I also try to respond to people's requests with
productive solutions and supportiveness if I will bother to say anything at
all. It simply isn't really helpful to say "refer to the docs".

Typically, when a developer has gotten to the point of using a product such
as React or Babble, they have more than likely been aware of readme
contents on the face of GitHub or something similar as the purpose of the
tools themselves are probably beyond an intro to HTML course. It was
condescending not to point out which section it is in, in the case that
someone may have overlooked something as well. I am probably just a bit
more direct than most people to say so. Beyond that, its not really worth
getting into a P.C. war about something like the choice of an open source
software product.

(And this response is not to downplay my appreciation with your response or
anything, just to explain my reaction!)

In any case, as most people who've been using MUI and React have done, I've
downgraded for now and things work fine. I'd been through the documentation
a few times, don't quite have the time in my work environment to thoroughly
troubleshoot these tools etc as we've got a tight deadline right now (I am
responding by phone at the moment). With another project, I am currently
using webpack but didn't want to migrate right now. I do appreciate the
offer to check it out though.

Thanks for the help.

**Comment by brunoscopelliti** [comment]
Hi @jmm 

I've the same issue too.
I've just made a sample repo, https://github.com/brunoscopelliti/babelify-issue-136. 

The demo use only the cli command.
I usually use only the cli commands, so i'm not really proficient with the api... and currently i have no time to explore (i will try for sure soon).

Let me know if there is anything else i can do.
Thank you

**Comment by jmm** [comment]
@brunoscopelliti Thanks for making the effort to create a repro. However, please note:

* It doesn't actually repro. That's why the [instructions](https://github.com/miniminirepro/miniminirepro/tree/6fbaedd02627ae562e343afc9edef10248de5639) end with:

  > Clone the repo you just pushed to a new directory and make sure it repros with your instructions.

  You have a dependency on a `get-world` module that isn't on npm or checked in to your repo.

* You deleted the instructions for running the repo from the [README](https://github.com/miniminirepro/babelify/blob/d21b3de2ba6ba5adeeb00da4fbd32dc7be0beea9/README.md). I only knew right off the bat how to try because I created that template.

* You're attempting to invoke a globally installed browserify, not the one you depend on.

* It's designed for the input to go in `src/entry` and the output to go in `dist/actual`.

Your problem is simple, [explained in the `README`](https://github.com/babel/babelify/blob/51693344ab1c4bda990b1fbe63769e9b88818473/README.md#why-arent-files-in-node_modules-being-transformed), a general issue with browserify (not specific to babelify), and likely not the same as either of the other posters in this issue. The same error message can be emitted for different reasons.

**Comment by jmm** [comment]
@rob2d 
> Thanks for all of the help Jesse.

Thanks, but it doesn't make sense to me that you've thanked me but not @zertosh. (FWIW, this kind of interaction tends to be very demotivating. And I can tell you from experience that some other open source maintainers would've responded to your comments angrily, and maybe put it on blast on twitter.)

> I typically do not have an issue interacting with others as I also try to respond to people's requests with productive solutions and supportiveness if I will bother to say anything at all.

Please understand that not bothering to say anything at all would be a very reasonable (and the easiest) response to someone posting a comment on a closed issue that was not actionable in the first place, especially without any new actionable information. Would you have preferred that?

> It simply isn't really helpful to say "refer to the docs".

By the same token, it's not helpful to file an issue that lacks basic information that would make it actionable while also including a bunch of extraneous information that's not relevant, which is what happened here. This was not a high quality report. Subsequent comments that don't add any information don't make it any more actionable.

Perhaps you're not aware of the context either. Babel v6 was released abruptly without coordination in the ecosystem, and with bug and documentation issues. This repo started getting a bunch of issues filed (and even [comments on old, unrelated issues](https://github.com/babel/babelify/issues/103#issuecomment-152548506)) for essentially the same problem: updating the major version without understanding what changed and without setting options for the version of Babel they were opting in to using.

> Typically, when a developer has gotten to the point of using a product such
as React or Babble, they have more than likely been aware of readme
contents on the face of GitHub or something similar as the purpose of the
tools themselves are probably beyond an intro to HTML course.

You might be surprised.

> It was condescending not to point out which section it is in, in the case that someone may have overlooked something as well.

Prior to replying to the OP @zertosh updated the `README` to lead with:

> As of [Babel 6.0.0](http://babeljs.io/blog/2015/10/29/6.0.0/) there are **no plugins included by default**. For babelify to be useful, you must also include some [presets](http://babeljs.io/docs/plugins/#presets) and/or [plugins](http://babeljs.io/docs/plugins/#transform).

And instead of just saying "there's not enough information to reproduce, please open a new issue with a minimal reproduction", which would've been totally appropriate based on the quality of the report, suggested the likely cause in the reply.

**Comment by brunoscopelliti** [comment]
Hi @jmm

Thanks for the fast answer.

Sorry for the poor repro... yesterday i was in a damn rush, and probably i would have done better to wait until today to submit the repro.

Thanks for the link, i've not tryed it yet, however it seems it should solve my problem.

**Comment by spoeken** [comment]
I had a similar problem connected to eslint. I added some parserOptions in my package.json and it all ran smooth. 

	  "eslintConfig": {
	    "env": {
	      "es6": true,
	      "node": true,
	      "browser": true
	    },
	    "parserOptions": {
	        "ecmaVersion": 6,
	        "sourceType": "module",
	        "ecmaFeatures": {
	            "jsx": true
	        }
	    },
	    "rules": {
	      "quotes": [
	        2,
	        "single"
	      ]
	    }
	  }

I hope this helps someone :)

**Comment by sourcec0de** [comment]
I resolved this issue by moving `babelify` out of `package.json` and using it as a global transform `browserify -g babelify`. Then I placed it's config in `.babelrc`

**Comment by aminnairi** [comment]
Solved this issue by appending the needed lines after the `devDependencies` in my `package.json` file:
```javascript
{
  "name": "browserify-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "gulp"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.25.0",
    "babel-preset-es2015": "^6.24.1",
    "babelify": "^7.3.0",
    "browserify": "^14.4.0",
    "gulp": "^3.9.1",
    "vue": "^2.4.1",
    "vueify": "^9.4.1"
  },
  "babel": {
      "presets": ["es2015"]
  },
  "browserify": {
      "transform": [
          [
              "babelify", {
                  "presets": ["es2015"]
              }
          ]
      ]
  }
}
```

**Comment by vielhuber** [comment]
@kumavis: Saved my day.
