### ISSUE TITLE
How to handle `emit('file')` with Babel presets?

### ISSUE THREAD

**Issue by mattdesl** [babel/babelify#173]
I'd like a Babel plugin to be able to emit a new dependency. How can we make this possible with babelify?

For example, I have a plugin that replaces `brfs` in some ways (with extra features like ES2015 and source maps).

https://github.com/Jam3/babel-plugin-static-fs

But the files will not get picked up by `watchify`. I can write a new source transform that wraps the above plugin with its own `babel-core` transform to support the file emitting, but it seems like it would be faster to use a single transform with multiple plugins (es2015, static-fs, etc).

**Comment by zertosh** [comment]
Hmm. What if the browserify instance is passed down as an option? Or if the plugin returned metadata about files that `babelify` should emit a `file` event for?

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babelify. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

This would be tough. This would need to be added to `babel/core` first, so either way if we explore this it should happen in https://github.com/babel/babel
