### ISSUE TITLE
transform babelify is slow since the very first run and it doesn't get better 

### ISSUE THREAD

**Issue by Geddard** [babel/babelify#212]
So i've been reading tons of posts about similar issues... I tried several different approaches with "watchify", none of the helped... seems my problem is not the same everyone used to have...

Here's my gulpfile:

``` javascript
// VENDOR LIBS
var browserify = require('browserify');
var buffer = require('vinyl-buffer');
var cleancss = require('gulp-clean-css');
var concat = require('gulp-concat');
var eslint = require('gulp-eslint');
var gulp = require('gulp');
var rimraf = require('rimraf');
var sass = require('gulp-sass');
var scsslint = require('gulp-scss-lint');
var source = require('vinyl-source-stream');
var uglify = require('gulp-uglify');

gulp.task('lint', function () {
    return gulp.src(['./app/**/*.js','!./node_modules/**', '!./dist/**'])
        .pipe(eslint())
        .pipe(eslint.format())
});

gulp.task('bundle', function () {
    return browserify({entries: './app/main.js', debug: true})
        .transform('babelify', {presets: ['es2015', 'react']})
        .bundle()
        .pipe(source('main.js'))
        .pipe(buffer())
        .pipe(uglify())
        .pipe(gulp.dest('dist'));
});

gulp.task('sass', function () {
    gulp.src('./app/components/**/*.scss')
        .pipe(scsslint({config: 'lint.yml'}))
        .pipe(sass())
        .pipe(concat('styles.css'))
        .pipe(cleancss())
        .pipe(gulp.dest('./dist'));
});

gulp.task('copy', ['lint', 'bundle', 'sass'], function () {
    return gulp.src(['app/index.html','app/lib/bootstrap-css/css/bootstrap.min.css','app/style.css'])
        .pipe(gulp.dest('dist'));
});

gulp.task('rimraf', function () {
    rimraf.sync('dist');
});

gulp.task('watch', ['copy'], function () {
    gulp.watch(['app/**/*', '!dist/**/*'], ['copy']);
});

gulp.task('build',['rimraf', 'watch'], function () {
   console.log('Gulp completed...');
});

gulp.task('default', ['build']);
```

It takes "bundle" around 7 second to finish (on the first and every subsequent run) and i'm barely starting with my project, so i'm worried this is going to get worse later :/

I tried removing the uglifier but it's the same and the file weights a lot more so that's a no-no...

Any ideas on how to make this thing go faster?

Thanks!

**Comment by Geddard** [comment]
nothing? :/

**Comment by DylanPiercey** [comment]
@Geddard I like to use https://github.com/ngryman/gulp-bro, makes it easier. Before this I was using https://github.com/jsdf/browserify-incremental.

**Comment by Geddard** [comment]
Thanks @DylanPiercey, but i'm pretty sure my problem is not that my build is not incremental, the build time doesn't get bigger on each repetition... it just takes a really long time always (around 7-8 seconds).

Do you happen to know how can i "browserify" my code without having to use babelify to transform it to ES5? and just throw ES6 code to the browser?

I don't care about old browsers that don't support it hehe

Thanks!

**Comment by DylanPiercey** [comment]
@Geddard I'm not 100℅ sure but I think you could achieve that using rollup js.

**Comment by StoneCypher** [comment]
I have a very similar problem.

If I manually build with babel at the command line, then browserify, the two together are about a quarter second.

If I use babelify, it's more like 20 seconds.

@Geddard - The reason in my case is actually sort of intentional: it's because I have babelify walking my entire dep tree, transforming any es6 into es5 for me.  So, for example, it's transforming react, and so on.  Sooner or later I'll extract react into a side package.

**Comment by BlueHotDog** [comment]
Same issue.. is bebelify active?

**Comment by hzoo** [comment]
The transforming part isn't that slow, if babel-cli is faster than browserify then it's just because bundling is slower or you are transpiling node_modules

**Comment by jrodriguesimg** [comment]
I have the same problem but I can't translate what @hzoo said into actions that I should take to reduce the build time. How do I avoid transpiling the node_modules?

**Comment by StoneCypher** [comment]
well there's a flag you can set to tell it not to

but if you need to do it manually, which is often actually necessary:

1) start thinking of your application as having two roots instead of one
2) one root is your es6 stuff.  transpile there.  bundle there.
3) the other root is your es5 stuff.  require the es5 stuff from the es6 stuff.  bundle again.

also, I get that webpack is a disaster, but browserify is no longer the right choice to avoid it.  go look into rollup instead.

**Comment by goto-bus-stop** [comment]
the OP is minifying the bundle too, and dependencies like react are quite large so depending on settings it can take a good while to minify. I'm not sure what gulp-uglify's defaults are, but running `terser -cm` on just react-dom's development build takes 4 seconds.

babelify does not run on dependencies _unless_ you pass `global: true`. see earlier related questions: #268 #276 #56

the primary way to speed up builds in development is using watchify, which will only re-transpile the files that changed: https://github.com/browserify/watchify
(and don't minify in development! :smile_cat: )

**Comment by amirkdv** [comment]
I have been having similar issues and in my case the root issue was not `babelify` but rather my usage of `browserify` and `watchify`. As per watchify [docs](https://github.com/browserify/watchify#watchifyb-opts):
> you MUST set the cache and packageCache properties

when creating the browserify instance (see code example below).
In my case, I cut down my build times in watch (i.e. after the first build) from ~ 8 seconds to ~ 1 second by going from:
```javascript
browserify(entry, {debug: true}).transform( ... )
```
to
```javascript
browserify(entry, {debug: true, cache: {}, packageCache: {}}).transform( ... )
```
Turning `debug` off further cuts the 1 second down to 0.1 second for me.

Given the language in watchify docs, I'm confused why things would even work (instead of work and be super slow) if those two properties are not set.
