### ISSUE TITLE
gulp, browserify babelify sourcemap with duplicate path

### ISSUE THREAD

**Issue by saidmoya12** [babel/babelify#223]
Goog afternoon.

I'm trying to enable the file editions from chrome but the sourcemap routes appear like:

> http://localhost:3000/js/app\app\app.js
> http://localhost:3000/js/app\bundles\Prototypes\app\bundles\Prototypes\index.js

I tryed to configure babelify like sourcemaps relative without solve it

Can I solve it?

Thanks.

### My Gulp File

```js
var appBundler = browserify({
	entries:	options.src, // Only need initial file, browserify finds the rest
	insertGlobals : true,
	harmony: 	true,
	debug:		options.development, // Gives us sourcemapping
	cache: {}, packageCache: {}, fullPaths: options.development // Requirement of watchify
}).transform(babelify);
```
```js
var start = Date.now();
appBundler
	.bundle()
	.on('error', gutil.log)
	.pipe(source('main.js'))
	.pipe(buffer())
	.pipe(gulp.dest(options.dest))
	.pipe(browserSync.stream())
	.pipe(notify(function () {
		console.log('APP bundle built in ' + (Date.now() - start) + 'ms');
	}));
```js

```

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babelify. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

If anyone has sourcemap issues in the future, please file a new issue with a reproducible repository.
