### ISSUE TITLE
babelify and tsify don't play nicely

### ISSUE THREAD

**Issue by Wkalmar** [babel/babelify#256]
Hi.
I've tried to build a pipeline TS -> ES6 -> ES5 which doesn't do even the simplest stuff. Somehow it confuses basic typescript syntax
gulpfile.js

```
var gulp = require('gulp');
var browserify = require('browserify');
var source = require('vinyl-source-stream');
var tsify = require('tsify');
var sourcemaps = require('gulp-sourcemaps');
var buffer = require('vinyl-buffer');
var tsc = require('typescript');

gulp.task('compile', function(){
    return browserify({
      basedir: '.',
      debug: true,
      entries: ['src/main.ts'],
      cache: {},
      packageCache: {}
  })
  .plugin(tsify, {typescript: tsc, global: true})
  .transform('babelify', {
      presets: ['es2015'],
      extensions: ['.ts']
  })
  .bundle()
  .pipe(source('bundle.js'));
  });
```

tsconfig.json
```
{
    "compilerOptions": {
        "noImplicitAny": true,
        "module": "commonjs",
        "target": "es6"
    }    
}
```

main.ts

```
const reallysimplestuff = (test: string[]) => {
    return "whoa this doesn't compile";
};
```

SyntaxError: D:/Programming/babelify-error-demo/src/main.ts: Unexpected token, expected , (1:31)
> 1 | const reallysimplestuff = (test: string[]) => {
    |                                                   ^
  2 |     return "whoa this doesn't compile";
  3 | };
I kindly ask you to point me what I am missing here

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babelify. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

The error seems to imply that the TS code isn't being converted fully, since Babel is still getting `: string[]` in it's input code.

**Comment by Macil** [comment]
The issue is because tsify is being used in global mode. In Browserify, global transforms run after regular transforms. You should only use tsify in global mode if there is uncompiled TypeScript under node_modules, which I don't think is standard. (NPM modules written in TypeScript shouldn't publish the source .ts files. [They should publish the compiled .js files and the generated .d.ts declaration files.](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html))
