### ISSUE TITLE
Function defined inside conditionals can't be accessed outside

### ISSUE THREAD

**Issue by PezCoder** [babel/babelify#259]
#### What ?
Sample code:
```js
 const someCondition = true;
 if (someCondition) {
   function insideFunc() {
     console.log('inside func');
   }
 }

 function someOtherFunc() {
   if (someCondition) {
     insideFunc();
   }
 }
```

After babelifying gives output like this:
```js
var someCondition = true;
if (someCondition) {
  var _insideFunc = function _insideFunc() {
    console.log('inside func');
  };
}

function someOtherFunc() {
  if (someCondition) {
    insideFunc();
  }
}
```

Notice the variable `insideFunc` this has been renamed inside the conditional with a suffix `_` but the reference isn't updated outside that conditional i.e inside `someOtherFunc`.
This code throws an error when executing  `someOtherFunc`, saying `insideFunc` is not defined.

#### My configurations
Package versions:
![screen shot 2018-03-08 at 8 11 56 pm](https://user-images.githubusercontent.com/8057916/37156835-2e82aff8-230d-11e8-88ff-8066f8d5bc12.png)

Gulp task
![screen shot 2018-03-08 at 8 12 36 pm](https://user-images.githubusercontent.com/8057916/37156768-0fcf4df0-230d-11e8-9b63-860079536a1d.png)

#### My attempt
1. the above is fixed if I define the insideFunc like this
```js
 var insideFunc = function() {
};
```
2. If i exclude `es2015` from presets in gulpfile, then the function names comes correctly

#### What could be permanent fix for this ? 
Really appreciate any help :)

**Comment by PezCoder** [comment]
Created a sample repository with minimal packages that reproduces the issue:
https://github.com/PezCoder/babel-function-issue-demo/blob/master/README.md

**Comment by loganfsmyth** [comment]
This issue is tracked in https://github.com/babel/babel/issues/5266 but it's not so much a bug as it is just currently unsupported and potentially something we won't support.

The issue is that
```
const someCondition = true;
if (someCondition) {
  function insideFunc() {
    console.log('inside func');
  }
}
```
is like you had written

```
const someCondition = true;
if (someCondition) {
  let insideFunc = function() {
    console.log('inside func');
  };
}
```
so the `insideFunc` variable only exists within the scope of the `if` block.

So why does your code work without the `es2015` transform? Because the specification allows this to _optionally_ work, when code is not running in strict mode. Since it is optional, and quite complex, Babel doesn't currently support it, and I honestly can't say if we will or not.

The best thing to do would be to rewrite your code as
```
const someCondition = true;
let insideFunc;
if (someCondition) {
  insideFunc = function() {
    console.log('inside func');
  }
}

function someOtherFunc() {
  if (someCondition) {
    insideFunc();
  }
}
```

**Comment by PezCoder** [comment]
@loganfsmyth This made me doubt my concepts of javascript I had learnt, Thank you for the enlightenment. 🥇 
I use to think that before executing a js program, the parser looks for all the function declarations & keeps them into memory doesn't matter if they are in conditionals or not, I think this is what used to happen in pre es6. 

But acc to es6 specs the functions declared inside blocks with have scopes only inside those blocks, same as having a let or const variable as you mentioned..

**Comment by loganfsmyth** [comment]
The issue is that in JS versions before ES6, function declarations inside of `if` blocks (and any non-function-body) actually weren't allowed at all and were not part of the specification.

Unfortunately, most of the engines had them anyway, but every engine treated them slightly differently. The "optional" feature I mentioned is the subset of behavior of all of the core engines that all behaved the same. It was specified as optional because it exists to define the behavior of existing engines in a standard way, not to be a requirement for future engines. That is also why the optional behavior is only for non-strict code.

**Comment by loganfsmyth** [comment]
So ES6 technically added support for functions inside of `if` blocks for the very first time in the history of the language, it just happens that engines already had them and they behaved badly :(

**Comment by PezCoder** [comment]
Just a tip for whoever goes ahead in testing different scenarios. Don't test it in the same console because the result of previous run alters the result of the next run. (it seriously messed up my head)
Use codepen or something.

**Comment by PezCoder** [comment]
@loganfsmyth It's great that they have it in the specifications now. I understand now that this isn't something babel should handle because for es5, the behaviour for this was very inconsistent as you mentioned.
Hence babel follows the current es6 specs for this when babelifying. It all makes sense now.
