### ISSUE TITLE
 babelify running on node_modules if an entry file is in node_modules

### ISSUE THREAD

**Issue by AgentME** [babel/babelify#85]
Possibly a Browserify bug?

```
$ npm i browserify babel babelify lodash
...
$ echo "import _ from 'lodash';" > index.js
$ ./node_modules/.bin/browserify -t babelify node_modules/babel/polyfill index.js -o out.js
[BABEL] Note: The code generator has deoptimised the styling of "/tmp/foo/node_modules/lodash/index.js" as it exceeds the max of "100KB".
```

**Comment by zertosh** [comment]
What you're seeing is the "auto" behavior of the ["compact" option](https://babeljs.io/docs/usage/options/). If you specify a value (either `true` or `false`), you won't get the warning:

```
browserify -t [ babelify --compact true ] node_modules/babel/polyfill index.js -o out.js
```

**Comment by AgentME** [comment]
Babelify shouldn't be transforming anything under node_modules. If you remove "node_modules/babel/polyfill" from the command, then you don't get that warning as it correctly avoids transforming anything under node_modules in that case.

**Comment by zertosh** [comment]
Ah, so because of [how](https://github.com/substack/module-deps/blob/f335ba8e240e42f328a41648efe2390b693dda39/index.js#L200-L208) browserify determines whether something is your module or not, by having one of your entries inside `node_modules`, it thinks everything there (excluding it's deps) are your files.

I'm guessing that you want `node_modules/babel/polyfill` as an entry so that it auto-runs w/o you having to explicitly require it? If you're really keen on this, you can do:

```sh
browserify -t [ babelify --ignore node_modules ] node_modules/babel/polyfill index.js -o out.js
```

But if you're not set on this pattern, you can always do:

```
echo "require('babel/polyfill'); import _ from 'lodash';" > index.js
browserify -t babelify index.js -o out.js
```

**Comment by AgentME** [comment]
Thanks for narrowing it down! I used to be able to run `browserify -t babelify babel/polyfill index.js -o out.js`, but it seems like browserify 10 made entries need to be filenames instead of anything that can be resolved, so when I changed the first entry to have the node_modules/ prefix, that must have triggered it.

**Comment by zertosh** [comment]
> but it seems like browserify 10 made entries need to be filenames instead of anything that can be resolved

@AgentME that was me :disappointed: We're working on sorting it out a consistent path resolution scheme. The idea is to have full paths internally, but let user input be all either fs-like (as in like when you use `fs.readFile`) or require-like - but not a weird mixture of both. You have a very interesting case though. Regardless of how you pass the path of `node_modules/babel/polyfill`, because it lives inside of `node_modules`, should all of its siblings be considered top level modules or not? You specified it as an entry, so my initial reaction is "yes", but that feels kinda wrong.

Sometimes I think that each plugin should decide for itself what files it transforms, instead of having browserify be a "gatekeeper". The distinction between "local" and "global" transforms makes sense, but then you end up with these weird edge cases.

I'm just ranting, sorry :)
