### ISSUE TITLE
Improve node_modules FAQ entry

### ISSUE THREAD

**Issue by ebednarz** [babel/babelify#90]
[FAQ](https://github.com/babel/babelify#faq):

> Why aren't files in node_modules being transformed?
   This is default browserify behaviour and can **not be** overriden. 

[That isn't correct](https://github.com/substack/node-browserify#btransformtr-opts), and if you just put application code in the `node_modules` directory to avoid relative `require` paths, it doesn't really make sense to have a `package.json` file there. For example, I usually put code in `node_modules/_app`, and this seems to work fine:

    .transform(babelify.configure({
        ignore: /\/node_modules\/(?!_app\/)/
    }), {
        global: true
    })

**Comment by zertosh** [comment]
That's one way to make it work - but I'd rather not endorse it

**Comment by zertosh** [comment]
I'm coming around on this. Maybe have it clearly labeled "Use at your own risk :skull:"

**Comment by ebednarz** [comment]
Sorry, I was busy and forgot about this. In any event the phrasing "can not be overridden" is not correct so I'd expect this to come back at some point.

Would you care to elaborate on the risk?

**Comment by zertosh** [comment]
> Would you care to elaborate on the risk?

The most glaring one is accidentally transforming a module. In theory this should be harmless because transforming ES5 should be a noop. But the `strict` transform is on by default, so people's code breaks because `'use strict'` is added to places it wasn't intended to. Look through the issues and you'll see this come up over and over again.

More subtly, global transforms run _after_ "local" transforms, so if you're running any other transform, and it can't parse ES5, it'll break.

So, given that these are advanced uses of the browserify api, I'm inclined to either not document it or just put a big warning. I'd welcome a PR that updates the docs, but that doesn't encourage this use and warns that you're on your own.
